### ISSUE TITLE
Replace lodash with lodash-es

### ISSUE THREAD

**Issue by Fuzzyma** [vimaec/vim-webgl-viewer#135]
Atm your bundle contains the WHOLE lodash lib even tho you are only using 2 functions from it. The lodash package doesn't seem to be tree shakeable. Thats why they have an es version which can be used the same way but is tree shakeable. That should bring down bundle size dramatically: https://www.npmjs.com/package/lodash-es

**Comment by vim-sroberge** [comment]
Thanks for noticing this.

**Comment by vim-sroberge** [comment]
Fixed in https://github.com/vimaec/vim-webgl-viewer/pull/138
