### ISSUE TITLE
Reference logo via cdn and position correctly

### ISSUE THREAD

**Issue by Fuzzyma** [vimaec/vim-webgl-viewer#14]
At the moment its just assumed, that the logo can be accessed in the server root but people only use your js lib. They wont host your images. To solve this, you could host the logo on your own server and reference it from there.

Furthermore, the logo is positioned with absolute coordinates. If your viewer is included on other pages, it will overlap with content of their page. Same is true for the GUI (that is broken if you try to hide it via settings btw). Both, GUI and logo should be positioned on the canvas or at least in a more intelligent manner

**Comment by cdiggins** [comment]
Thanks a lot for the feedback Fuzzyma.
