### ISSUE TITLE
Settings Hotkey Update to Ctrl+'/'

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#224]
All users need the ability to summon the VIM Visualization settings within a Power BI report within any desktop web browser so that they can turn various tools on and off to complete their various tasks.

**Issue:** At the moment, our hotkeys are tied to Function keys, and most browsers have these reserved. 

Solution: We need to reassign keyboard commands, starting with settings. We will review our existing list and see if there are any other low-hanging opportunities while we're at it.

Edge: https://support.microsoft.com/en-us/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad

![Image](https://github.com/vimaec/vim-webgl-viewer/assets/63117264/115a1911-8d35-4af2-8966-ab8e5181dd4b)

![Image](https://github.com/vimaec/vim-webgl-viewer/assets/63117264/08c34e52-5e16-4555-b924-3dffe6d2f56f)

**Comment by skyw4kr** [comment]
Ctrl+/ is reserved by several web apps to summon a command bar, since we can't do that within the overall context of PowerBI, I suggest we use this keyboard combo to summon the user settings panel.

**Comment by skyw4kr** [comment]
I suspected adding this feature would mean we must republish each report. This could also be a chance to update:

- Backgrounds with new title bar visual
- Add video buttons (if we use a shortcut url we can always direct to videos when they're done later)
- Clean up formatting with some recent updates
- Each report will get the latest data set?
- Any improvements we've been holding off on

Or do we want to wait until the new publishing process is complete?
