### ISSUE TITLE
Add a spinner for showing progress while loading the VIM 

### ISSUE THREAD

**Issue by vim-sroberge** [vimaec/vim-webgl-viewer#23]
See: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_loader

**Comment by cdiggins** [comment]
To avoid React depednency, could use this JavaScript code in HTML page to Hide/Show: https://stackoverflow.com/questions/6242976/javascript-hide-show-element. 
Or use Add/Remove child. 
And to change the text: https://www.w3schools.com/js/js_htmldom_html.asp
