### ISSUE TITLE
Hover the mouse over the model and capture the pointer to the nearest edge or vertex

### ISSUE THREAD

**Issue by wwjje** [vimaec/vim-webgl-viewer#258]
Pointer capture adsorption is a very important function. Can it be added to this project?
Here are some examples and references
https://xeokit.github.io/xeokit-sdk/examples/picking/#snapToEdge
https://github.com/tmarti/graphics-research/blob/main/articles/webgl2-gpu-based-snapping.md
![image](https://github.com/user-attachments/assets/4c657262-298d-4b4c-a92c-e36f47dbb94c)

**Comment by mavimaec** [comment]
Hi @wwjje , we will keep this suggestion in mind for the future. Currently this feature is not within our development roadmap.
