### ISSUE TITLE
viewer blocks default key behavior

### ISSUE THREAD

**Issue by Fuzzyma** [vimaec/vim-webgl-viewer#76]
the viewer seem to consume all keydown events. So f12 to open the devtools doesn't work as well as f5 to refresh the page. Thats kinda annoying. Better only catch the cases you want to react on and let the other cases fall through

**Comment by cdiggins** [comment]
I think this is related to: https://github.com/vimaec/vim-webgl-viewer/issues/66. 
Also blocks F11 (Full-Screen mode).
