### ISSUE TITLE
Canvas doesnt resize when window is changed

### ISSUE THREAD

**Issue by vim-sroberge** [vimaec/vim-webgl-viewer#89]

**Comment by cdiggins** [comment]
As a user of the API, I want to pass the canvas id in to the viewer, instead of the viewer adding to the canvas. This way canvas styling and resizing is purely the responsibility of the viewer host (e.g. a web page, or an app).

**Comment by vim-sroberge** [comment]
Yep it is supported now, that's what the app does :D
https://github.com/vimaec/vim-webgl-app/blob/main/src/vimWebApp.ts

**Comment by cdiggins** [comment]
That is great! I would consider taking it even a step further, and suggest that it is mandatory that the canvas id is passed in, and using it in your examples here. This allows you to remove all canvas handling code from the viewer, and not have to support issues like this one (#89). 

Or alternatively, you just document it (along with all of the options), and close the issue with a "see the docs" comment. :-)
